/* eslint-disable jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions */
"use client";

import { useEffect, useMemo, useState } from "react";
import "./os.css";

type RecordItem = { id:string; module:string; title:string; client:string; status:string; amount?:number; qty?:number; due?:string; phone?:string; detail?:string; progress?:number };
type Store = { records:RecordItem[]; activities:string[]; notifications:string[] };

const modules = ["Dashboard","CRM","Clients","Requirements","Styles","Costings","Quotations","Orders","Production","Samples","Procurement","Calendar","Invoices","Payments","Vendors","Tasks","Files","Reports","Portal","Settings"];
const icons:Record<string,string>={Dashboard:"⌂",CRM:"◎",Clients:"◉",Requirements:"≡",Styles:"◇",Costings:"৳",Quotations:"▱",Orders:"□",Production:"◆",Samples:"△",Procurement:"⇄",Calendar:"▦",Invoices:"▤",Payments:"$",Vendors:"⬡",Tasks:"✓",Files:"⌁",Reports:"◒",Portal:"↗",Settings:"⚙"};
const statuses:Record<string,string[]>={CRM:["New Lead","Contacted","Qualified","Requirement Received","Quotation Sent","Negotiation","Sample","Won","Lost"],Orders:["Draft","Awaiting Advance","Confirmed","Pre-production","In Production","QC","Ready","Delivered","Completed"],Production:["Planning","Material Sourcing","Cutting","Printing","Embroidery","Sewing","Finishing","QC","Packing","Ready","Completed"],Quotations:["Draft","Sent","Viewed","Negotiating","Accepted","Rejected","Expired","Converted"],Samples:["Requested","In Development","Ready","Sent to Client","Revision Requested","Approved","Rejected"],Invoices:["Draft","Sent","Partial","Paid","Overdue","Cancelled"],Tasks:["Open","In Progress","Done"],Requirements:["Draft","Costing","Quoted","Ordered"],Costings:["Draft","Approved","Quoted"],Procurement:["Ordered","Partially Received","Received"],Payments:["Received"],Clients:["Active","Inactive"],Vendors:["Active","Review"],Calendar:["Scheduled","Done"],Files:["Available"],Styles:["Active"]};
const seed:Store={records:[
 {id:"APH-LEAD-2026-0041",module:"CRM",title:"ABC Fashion",client:"Rahim",status:"Quotation Sent",amount:242500,qty:500,due:"Tomorrow",phone:"01712345678",detail:"220 GSM oversized T-shirt"},
 {id:"APH-LEAD-2026-0042",module:"CRM",title:"Urban Thread",client:"Sadia",status:"Qualified",amount:380000,qty:800,due:"20 Aug",phone:"01812345678",detail:"Heavyweight hoodie"},
 {id:"CL-1001",module:"Clients",title:"ABC Fashion",client:"Rahim · Owner",status:"Active",amount:1840000,phone:"01712345678",detail:"3 active orders · ৳105K outstanding"},
 {id:"REQ-1024",module:"Requirements",title:"Oversized Drop Shoulder T-shirt",client:"ABC Fashion",status:"Costing",qty:500,due:"30 Sep",detail:"Cotton compact single jersey · 220 GSM · Black"},
 {id:"APH-ST-0028",module:"Styles",title:"Core Oversized Tee",client:"Unisex",status:"Active",detail:"220 GSM · Single Jersey · S–XXL"},
 {id:"APH-CST-1042-V3",module:"Costings",title:"220 GSM Oversized Tee",client:"ABC Fashion",status:"Approved",amount:1205,detail:"Cost ৳1,004 · Margin 20% · Per piece"},
 {id:"APH-Q-2026-0042",module:"Quotations",title:"Oversized Tee · 500 pcs",client:"ABC Fashion",status:"Accepted",amount:242500,due:"Valid 7 days",detail:"৳485 / pc · 50% advance"},
 {id:"APH-ORD-2026-1042",module:"Orders",title:"Oversized Tee",client:"ABC Fashion",status:"In Production",amount:242500,qty:500,due:"26 Aug",progress:72,detail:"Paid ৳121,250 · Balance ৳121,250"},
 {id:"APH-ORD-2026-1038",module:"Orders",title:"Heavyweight Hoodie",client:"Northstar Retail",status:"QC",amount:384000,qty:320,due:"22 Aug",progress:86,detail:"Paid ৳192,000 · Balance ৳192,000"},
 {id:"APH-PJ-1042",module:"Production",title:"Oversized Tee",client:"ABC Fashion",status:"Sewing",qty:500,due:"26 Aug",progress:72,detail:"Cut 510 · Sewn 360 · Rejected 4"},
 {id:"APH-PJ-1038",module:"Production",title:"Heavyweight Hoodie",client:"Northstar Retail",status:"Finishing",qty:320,due:"22 Aug",progress:86,detail:"Sewn 318 · Finished 290 · Rejected 2"},
 {id:"APH-SMP-1008-V3",module:"Samples",title:"Black Oversized Tee",client:"ABC Fashion",status:"Approved",due:"18 Aug",detail:"Pre-production sample · Version 3"},
 {id:"APH-PO-0241",module:"Procurement",title:"220 GSM Black Fabric",client:"Dhaka Knit Mills",status:"Partially Received",amount:338000,qty:650,due:"19 Aug",detail:"Received 520 kg · Balance 130 kg"},
 {id:"EVT-101",module:"Calendar",title:"Sample review",client:"ABC Fashion",status:"Scheduled",due:"Today · 3:00 PM",detail:"Video meeting · Jahid + Rahim"},
 {id:"APH-INV-2026-1042",module:"Invoices",title:"Final invoice",client:"ABC Fashion",status:"Partial",amount:242500,due:"26 Aug",detail:"Paid ৳121,250 · Outstanding ৳121,250"},
 {id:"PAY-2031",module:"Payments",title:"Bank transfer",client:"ABC Fashion",status:"Received",amount:121250,due:"16 Aug",detail:"Advance · Ref DBBL-88419"},
 {id:"VEN-010",module:"Vendors",title:"Dhaka Knit Mills",client:"Fabric Supplier",status:"Active",detail:"On-time 92% · Rating 4.7 · MOQ 300 kg"},
 {id:"TSK-0281",module:"Tasks",title:"Confirm print strike-off",client:"Mora Studio",status:"Open",due:"Today",detail:"High priority · Assigned to Jahid"},
 {id:"FILE-182",module:"Files",title:"ABC-Tech-Pack-v4.pdf",client:"ABC Fashion",status:"Available",detail:"Requirement REQ-1024 · 4.2 MB"}
],activities:["Quotation APH-Q-2026-0042 accepted","Black Hoodie sample approved","Payment ৳121,250 received","APH-PJ-1042 moved to Sewing","Invoice APH-INV-2026-1042 sent"],notifications:["Production deadline in 2 days","Sample approved by ABC Fashion","Payment received · ৳121,250"]};

const money=(n=0)=>`৳${new Intl.NumberFormat("en-BD").format(n)}`;
const wa=(phone="")=>`https://wa.me/${phone.replace(/\D/g,"").replace(/^0/,"880")}`;
const key="aphuranta-os-v2";

export default function AphurantaOS(){
 const [store,setStore]=useState<Store>(()=>{if(typeof window==="undefined")return seed;try{const saved=localStorage.getItem(key);return saved?JSON.parse(saved):seed}catch{return seed}}); const [active,setActive]=useState("Dashboard"); const [query,setQuery]=useState(""); const [search,setSearch]=useState(false); const [create,setCreate]=useState(false); const [selected,setSelected]=useState<RecordItem|null>(null); const [toast,setToast]=useState(""); const [more,setMore]=useState(false);
 useEffect(()=>{localStorage.setItem(key,JSON.stringify(store))},[store]);
 const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};
 const openModule=(x:string)=>{setActive(x);setSelected(null);setMore(false);window.scrollTo({top:0,behavior:"smooth"})};
 const results=useMemo(()=>{const q=query.toLowerCase().trim();return q?store.records.filter(r=>Object.values(r).join(" ").toLowerCase().includes(q)).slice(0,12):store.records.slice(0,8)},[query,store.records]);
 const moduleRecords=store.records.filter(r=>r.module===active);
 const save=(record:RecordItem)=>{setStore(s=>({...s,records:[record,...s.records],activities:[`${record.id} created`,...s.activities]}));setCreate(false);openModule(record.module);notify(`${record.id} created`)};
 const update=(record:RecordItem)=>{setStore(s=>({...s,records:s.records.map(r=>r.id===record.id?record:r),activities:[`${record.id} updated to ${record.status}`,...s.activities]}));setSelected(record);notify("Update saved")};
 return <main className="os-shell">
  <aside className="os-sidebar"><Brand/><nav>{modules.map(x=><button key={x} className={active===x?"active":""} onClick={()=>openModule(x)}><span>{icons[x]}</span>{x}{x==="Tasks"&&<b>{store.records.filter(r=>r.module==="Tasks"&&r.status!=="Done").length}</b>}</button>)}</nav><div className="user"><i>JS</i><div><strong>Jahid S.</strong><small>Administrator</small></div></div></aside>
  <section className="os-work"><header className="os-top"><div className="mobile-brand"><Brand/></div><button className="global-search" onClick={()=>setSearch(true)}>⌕ <span>Search clients, phone, order, invoice…</span><kbd>⌘ K</kbd></button><button className="add" onClick={()=>setCreate(true)}>＋ <span>Quick create</span></button><button className="bell" onClick={()=>openModule("Dashboard")}>♢<i/></button><i className="top-avatar">JS</i></header>
   {selected?<Detail item={selected} onBack={()=>setSelected(null)} onUpdate={update}/>:active==="Dashboard"?<Dashboard store={store} open={openModule} select={setSelected}/>:active==="Reports"?<Reports store={store}/>:active==="Settings"?<Settings notify={notify}/>:active==="Portal"?<Portal store={store} update={update}/>:<ModulePage name={active} rows={moduleRecords} select={setSelected} create={()=>setCreate(true)}/>} 
  </section>
  <button className="fab" onClick={()=>setCreate(true)}>＋</button><nav className="mobile-nav"><button className={active==="Dashboard"?"active":""} onClick={()=>openModule("Dashboard")}>⌂<small>Home</small></button><button className={active==="CRM"?"active":""} onClick={()=>openModule("CRM")}>◎<small>CRM</small></button><span/><button className={active==="Orders"?"active":""} onClick={()=>openModule("Orders")}>□<small>Orders</small></button><button onClick={()=>setMore(true)}>☰<small>More</small></button></nav>
  {search&&<Search query={query} setQuery={setQuery} results={results} close={()=>setSearch(false)} select={r=>{setSearch(false);openModule(r.module);setSelected(r)}}/>}
  {create&&<CreateSheet close={()=>setCreate(false)} save={save}/>} {more&&<MoreSheet close={()=>setMore(false)} open={openModule}/>} {toast&&<div className="os-toast">✓ {toast}</div>}
 </main>
}

function Brand(){return <div className="brand"><i>A</i><div><strong>APHURANTA</strong><small>APPAREL OPERATIONS</small></div></div>}
function Dashboard({store,open,select}:{store:Store;open:(x:string)=>void;select:(r:RecordItem)=>void}){const jobs=store.records.filter(r=>r.module==="Production");return <div className="os-page"><header className="page-title"><div><p>SUNDAY, 16 AUGUST</p><h1>Good morning, Jahid.</h1><span>Here’s the pulse of Aphuranta today.</span></div><button>This month⌄</button></header><section className="metrics"><Metric label="Revenue" value="৳18.4L" meta="↑ 8.2% this month" hero/><Metric label="Active orders" value="12" meta="4 due this week"/><Metric label="Outstanding" value="৳4.2L" meta="৳85K overdue"/><Metric label="Active production" value="8" meta="2 need attention"/><Metric label="Pending quotes" value="6" meta="৳4.2L value"/><Metric label="Pending samples" value="4" meta="1 awaiting approval"/><Metric label="Due soon" value="4" meta="Next 7 days"/><Metric label="Overdue jobs" value="2" meta="Action required"/></section><section className="today"><strong>● TODAY</strong><button onClick={()=>open("CRM")}>3 Follow-ups ›</button><button onClick={()=>open("Production")}>2 Production deadlines ›</button><button onClick={()=>open("Invoices")}>1 Payment due ›</button></section><div className="dash-grid"><Panel title="Active production" kicker="LIVE OPERATIONS" action={()=>open("Production")}><div className="job-grid">{jobs.map(j=><RecordCard key={j.id} r={j} select={select}/>)}</div></Panel><Panel title="Upcoming deadlines" kicker="COMING UP" action={()=>open("Calendar")}><div className="timeline">{store.records.filter(r=>r.due).slice(0,5).map(r=><button key={r.id} onClick={()=>select(r)}><i>{r.due?.slice(0,2)}</i><span><strong>{r.title}</strong><small>{r.client} · {r.due}</small></span><b>›</b></button>)}</div></Panel></div><div className="dash-grid"><Panel title="Sales pipeline" kicker="COMMERCIAL" action={()=>open("CRM")}><div className="pipeline">{["New Lead","Qualified","Quotation Sent","Negotiation","Won"].map((x,i)=><div key={x}><span>{x}</span><strong>{[14,8,6,3,9][i]}</strong><i><b style={{width:`${90-i*10}%`}}/></i></div>)}</div></Panel><Panel title="Recent activity" kicker="AUDIT TRAIL"><ul className="activity">{store.activities.slice(0,5).map(x=><li key={x}>{x}<small>Recently</small></li>)}</ul></Panel></div></div>}
function Metric({label,value,meta,hero=false}:{label:string;value:string;meta:string;hero?:boolean}){return <article className={hero?"metric hero":"metric"}><span>{label}</span><strong>{value}</strong><small>{meta}</small></article>}
function Panel({title,kicker,children,action}:{title:string;kicker:string;children:React.ReactNode;action?:()=>void}){return <section className="os-panel"><header><div><p>{kicker}</p><h2>{title}</h2></div>{action&&<button onClick={action}>View all →</button>}</header>{children}</section>}
function ModulePage({name,rows,select,create}:{name:string;rows:RecordItem[];select:(r:RecordItem)=>void;create:()=>void}){const [view,setView]=useState("List");return <div className="os-page"><header className="module-head"><div><p>APHURANTA · {name.toUpperCase()}</p><h1>{name}</h1><span>{rows.length} connected records</span></div><button className="primary" onClick={create}>＋ New {name.replace(/s$/,"")}</button></header><div className="toolbar"><div><button className={view==="List"?"active":""} onClick={()=>setView("List")}>☷ List</button>{name==="CRM"&&<button className={view==="Pipeline"?"active":""} onClick={()=>setView("Pipeline")}>▦ Pipeline</button>}</div><button>☷ Filters</button></div>{view==="Pipeline"?<Kanban rows={rows} select={select}/>:<><div className="record-table"><header><span>Record</span><span>Client / Contact</span><span>Status</span><span>Value / Quantity</span><span>Due</span></header>{rows.map(r=><RecordRow key={r.id} r={r} select={select}/>)}</div><div className="record-cards">{rows.map(r=><RecordCard key={r.id} r={r} select={select}/>)}</div></>}</div>}
function RecordRow({r,select}:{r:RecordItem;select:(x:RecordItem)=>void}){return <button onClick={()=>select(r)}><span><strong>{r.title}</strong><small>{r.id} · {r.detail}</small></span><span>{r.client}</span><span><i className="pill">{r.status}</i></span><span>{r.amount?money(r.amount):r.qty?`${r.qty} pcs`:"—"}</span><span>{r.due||"—"}　›</span></button>}
function RecordCard({r,select}:{r:RecordItem;select:(x:RecordItem)=>void}){return <article className="record-card" onClick={()=>select(r)}><header><i className="pill">{r.status}</i><small>{r.id}</small></header><h3>{r.title}</h3><p>{r.client} · {r.detail}</p>{typeof r.progress==="number"&&<><div className="progress-label"><span>Progress</span><strong>{r.progress}%</strong></div><div className="bar"><i style={{width:`${r.progress}%`}}/></div></>}<footer><strong>{r.amount?money(r.amount):r.qty?`${r.qty} pcs`:r.due||"Open record"}</strong><button>Open →</button></footer></article>}
function Kanban({rows,select}:{rows:RecordItem[];select:(r:RecordItem)=>void}){const stages=statuses.CRM.slice(0,8);return <div className="kanban">{stages.map(s=><section key={s}><header><strong>{s}</strong><b>{rows.filter(r=>r.status===s).length}</b></header>{rows.filter(r=>r.status===s).map(r=><RecordCard key={r.id} r={r} select={select}/>)}</section>)}</div>}
function Detail({item,onBack,onUpdate}:{item:RecordItem;onBack:()=>void;onUpdate:(r:RecordItem)=>void}){const [status,setStatus]=useState(item.status);const [progress,setProgress]=useState(item.progress||0);return <div className="os-page detail"><button className="back" onClick={onBack}>← Back to {item.module}</button><header className="detail-head"><div><p>{item.module.toUpperCase()} · {item.id}</p><h1>{item.title}</h1><span>{item.client}</span></div><i className="pill large">{status}</i></header><section className="summary"><Metric label="Value" value={item.amount?money(item.amount):item.qty?`${item.qty} pcs`:"Active"} meta={item.detail||"Connected record"}/><Metric label="Status" value={status} meta={item.due?`Due ${item.due}`:"Up to date"}/><Metric label="Progress" value={`${progress}%`} meta="Calculated from workflow stages"/><Metric label="Activity" value="12" meta="Timeline events"/></section><div className="detail-grid"><Panel title="Workflow & details" kicker="ONE CONNECTED RECORD"><div className="fields"><label>Current status<select value={status} onChange={e=>setStatus(e.target.value)}>{(statuses[item.module]||[item.status]).map(x=><option key={x}>{x}</option>)}</select></label>{item.module==="Production"&&<label>Progress<input type="range" min="0" max="100" value={progress} onChange={e=>setProgress(+e.target.value)}/><b>{progress}%</b></label>}<label>Client / vendor<input value={item.client} readOnly/></label><label>Reference<input value={item.id} readOnly/></label><label className="wide">Notes<textarea defaultValue={item.detail}/></label><button className="primary" onClick={()=>onUpdate({...item,status,progress})}>Save update</button></div></Panel><Panel title="Actions" kicker="NEXT BEST STEP"><div className="actions">{item.phone&&<><a href={`tel:${item.phone}`}>☎ Call</a><a href={wa(item.phone)} target="_blank">◉ WhatsApp</a></>}<button onClick={()=>onUpdate({...item,status:(statuses[item.module]||[item.status])[Math.min((statuses[item.module]||[]).indexOf(status)+1,(statuses[item.module]||[]).length-1)]||status})}>→ Move to next stage</button><button>＋ Add task</button><button>⌁ Upload file</button><label className="camera">▣ Take production photo<input type="file" accept="image/*" capture="environment"/></label></div></Panel></div><Panel title="Activity timeline" kicker="AUDIT LOG"><ul className="activity"><li>{item.id} viewed<small>Just now · Jahid S.</small></li><li>Status is {status}<small>Today · System</small></li><li>Record created from connected workflow<small>16 Aug · Aphuranta OS</small></li></ul></Panel><div className="sticky-actions"><button onClick={onBack}>Back</button><button className="primary" onClick={()=>onUpdate({...item,status,progress})}>Save update</button></div></div>}
function CreateSheet({close,save}:{close:()=>void;save:(r:RecordItem)=>void}){const [module,setModule]=useState("CRM");const [title,setTitle]=useState("");const [client,setClient]=useState("");const [amount,setAmount]=useState("");const [phone,setPhone]=useState("");const submit=()=>{if(!title||!client)return;const prefix:Record<string,string>={CRM:"LEAD",Clients:"CL",Requirements:"REQ",Costings:"CST",Quotations:"Q",Orders:"ORD",Production:"PJ",Samples:"SMP",Invoices:"INV",Payments:"PAY",Vendors:"VEN",Tasks:"TSK"};save({id:`APH-${prefix[module]||module.slice(0,3).toUpperCase()}-${Date.now().toString().slice(-6)}`,module,title,client,status:(statuses[module]||["Active"])[0],amount:+amount||undefined,phone:phone||undefined,due:"Today",detail:"Created from Quick Create"})};return <div className="overlay" onMouseDown={close}><section className="sheet" onMouseDown={e=>e.stopPropagation()}><i className="handle"/><header><div><p>ADD TO APHURANTA</p><h2>Quick create</h2></div><button onClick={close}>×</button></header><div className="type-grid">{["CRM","Clients","Requirements","Costings","Quotations","Orders","Production","Samples","Invoices","Payments","Tasks","Calendar","Vendors"].map(x=><button className={module===x?"active":""} onClick={()=>setModule(x)} key={x}>{icons[x]}<small>{x}</small></button>)}</div><div className="create-form"><label>{module==="CRM"?"Company / lead name":"Title"}<input value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></label><label>Client / contact<input value={client} onChange={e=>setClient(e.target.value)}/></label><label>Amount<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Phone<input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label><button className="primary" disabled={!title||!client} onClick={submit}>Create {module.replace(/s$/,"")}</button></div></section></div>}
function Search({query,setQuery,results,close,select}:{query:string;setQuery:(x:string)=>void;results:RecordItem[];close:()=>void;select:(r:RecordItem)=>void}){return <div className="overlay search-layer" onMouseDown={close}><section className="search-box" onMouseDown={e=>e.stopPropagation()}><header>⌕<input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Aphuranta…"/><button onClick={close}>ESC</button></header><p>CLIENTS, PHONE, ORDERS, INVOICES, JOBS & SUPPLIERS</p>{results.map(r=><button key={r.id} onClick={()=>select(r)}><i>{icons[r.module]}</i><span><strong>{r.title}</strong><small>{r.module} · {r.id} · {r.client}</small></span><b>→</b></button>)}</section></div>}
function MoreSheet({close,open}:{close:()=>void;open:(x:string)=>void}){return <div className="overlay" onMouseDown={close}><section className="sheet more" onMouseDown={e=>e.stopPropagation()}><i className="handle"/><header><h2>All modules</h2><button onClick={close}>×</button></header><div className="type-grid">{modules.map(x=><button key={x} onClick={()=>open(x)}>{icons[x]}<small>{x}</small></button>)}</div></section></div>}
function Reports({store}:{store:Store}){const revenue=store.records.filter(r=>r.module==="Invoices").reduce((a,r)=>a+(r.amount||0),0);return <div className="os-page"><header className="module-head"><div><p>MANAGEMENT INTELLIGENCE</p><h1>Reports & analytics</h1><span>Live connected business indicators</span></div><button className="primary">Export report</button></header><section className="metrics"><Metric label="Invoiced" value={money(revenue)} meta="Current records" hero/><Metric label="Collected" value="৳121,250" meta="50% collection rate"/><Metric label="Gross margin" value="20.4%" meta="↑ 2.1%"/><Metric label="On-time delivery" value="88%" meta="Last 90 days"/></section><div className="dash-grid"><Panel title="Revenue trend" kicker="FINANCE"><div className="chart">{[38,52,44,68,73,60,86,71,92,84,96,100].map((x,i)=><i key={i} style={{height:`${x}%`}}><small>{["S","O","N","D","J","F","M","A","M","J","J","A"][i]}</small></i>)}</div></Panel><Panel title="Client profitability" kicker="TOP CLIENTS"><div className="ranking"><span>ABC Fashion <b>৳6.4L · 24%</b></span><span>Northstar Retail <b>৳4.8L · 22%</b></span><span>Mora Studio <b>৳2.1L · 19%</b></span></div></Panel></div></div>}
function Portal({store,update}:{store:Store;update:(r:RecordItem)=>void}){const order=store.records.find(r=>r.module==="Orders")!;const sample=store.records.find(r=>r.module==="Samples")!;return <div className="os-page portal"><header className="portal-head"><Brand/><button>Client sign out</button></header><div className="welcome"><p>CLIENT PORTAL</p><h1>Welcome, ABC Fashion.</h1><span>Your orders, approvals, invoices and files in one place.</span></div><section className="summary"><Metric label="Active order" value="1" meta="500 pcs · Delivery 26 Aug" hero/><Metric label="Pending approval" value="1" meta="Sample version 3"/><Metric label="Outstanding" value="৳121,250" meta="Due 26 Aug"/><Metric label="Files" value="8" meta="2 added recently"/></section><div className="dash-grid"><Panel title="Active order" kicker={order.id}><RecordCard r={order} select={()=>{}}/></Panel><Panel title="Sample approval" kicker={sample.id}><div className="approval"><div className="sample-image">A</div><h3>{sample.title}</h3><p>{sample.detail}</p><button>Request change</button><button className="primary" onClick={()=>update({...sample,status:"Approved"})}>✓ Approve sample</button></div></Panel></div></div>}
function Settings({notify}:{notify:(x:string)=>void}){return <div className="os-page"><header className="module-head"><div><p>ADMINISTRATION</p><h1>Settings</h1><span>Organization, people, workflow and controls</span></div></header><div className="settings-grid">{["Company profile","Users & roles","Number sequences","Production weights","Currencies & tax","Payment terms","Notifications","Automation rules","File storage","Audit log"].map((x,i)=><button key={x} onClick={()=>notify(`${x} settings saved`)}><i>{["A","JS","#","%","৳","▤","♢","⚡","⌁","✓"][i]}</i><span><strong>{x}</strong><small>Configure and manage {x.toLowerCase()}</small></span><b>›</b></button>)}</div></div>}
